package gestoria;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.EncryptedDocumentException;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;

/**
 *
 * @author jadelabe
 */
public class gui extends javax.swing.JFrame {

    static Vector headers = new Vector();
    static Vector data = new Vector();
    static DefaultTableModel model = null;
    static JButton jbClick;
    static JFileChooser jChooser;
    static int tableWidth = 0;
    static int tableHeight = 0;

    String fecha = "";

    public static void fillData() {
        Workbook workbook = null;

        try {
            try {
                FileInputStream inputStream = new FileInputStream("./src/gestoria/PracticaIV.xlsx");
                workbook = WorkbookFactory.create(inputStream);
            } catch (IOException ex) {
                System.out.println(ex);
            }
            Sheet sheet = workbook.getSheet("Hoja1");
            Row row = sheet.getRow(0);

            headers.clear();
            for (int i = 0; i < row.getLastCellNum(); i++) {
                Cell cell1 = row.getCell(i);
                headers.add(cell1.toString());
            }

            data.clear();
            for (int j = 1; j < sheet.getLastRowNum() + 1; j++) {
                Vector d = new Vector();
                row = sheet.getRow(j);
                int noofrows = row.getLastCellNum();
                for (int i = 0; i < noofrows; i++) {    //To handle empty excel cells 
                    Cell cell = row.getCell(i, org.apache.poi.ss.usermodel.Row.CREATE_NULL_AS_BLANK);
                    d.add(cell.toString());
                }
                d.add("\n");
                data.add(d);
            }
        } catch (InvalidFormatException | EncryptedDocumentException ex) {
            System.out.println(ex);
        }
    }

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionarFecha = new javax.swing.JDialog();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        Mes = new javax.swing.JComboBox<>();
        Año = new javax.swing.JComboBox<>();
        Meslbl = new javax.swing.JLabel();
        Añolbl = new javax.swing.JLabel();
        about = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        help = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuTrabajador = new javax.swing.JMenu();
        jMenuDNI = new javax.swing.JMenuItem();
        jMenuIBAN = new javax.swing.JMenuItem();
        jMenuCorreo = new javax.swing.JMenuItem();
        jMenuNomina = new javax.swing.JMenu();
        jMenuGenerarNomina = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuAyudaa = new javax.swing.JMenuItem();
        jMenuInformacion = new javax.swing.JMenuItem();

        seleccionarFecha.setTitle("Seleccionar Fecha");
        seleccionarFecha.setModal(true);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        Mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        Año.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));

        Meslbl.setText("Mes");

        Añolbl.setText("Año");

        javax.swing.GroupLayout seleccionarFechaLayout = new javax.swing.GroupLayout(seleccionarFecha.getContentPane());
        seleccionarFecha.getContentPane().setLayout(seleccionarFechaLayout);
        seleccionarFechaLayout.setHorizontalGroup(
            seleccionarFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionarFechaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seleccionarFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Meslbl)
                    .addComponent(Aceptar)
                    .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(seleccionarFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelar)
                    .addComponent(Añolbl))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        seleccionarFechaLayout.setVerticalGroup(
            seleccionarFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seleccionarFechaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(seleccionarFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Meslbl)
                    .addComponent(Añolbl))
                .addGap(10, 10, 10)
                .addGroup(seleccionarFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seleccionarFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(Cancelar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        about.setTitle("Informacion");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Autores:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Javier de Lama Bermejo");

        jLabel3.setText("jlamab00@estudiantes.unileon.es");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Patricia tur Bañon");

        jLabel5.setText("pturba00@estudiantes.unileon.es");

        jLabel6.setText("Sistemas de Información II");

        jLabel7.setText("Universidad de León");

        jLabel8.setText("2016");

        javax.swing.GroupLayout aboutLayout = new javax.swing.GroupLayout(about.getContentPane());
        about.getContentPane().setLayout(aboutLayout);
        aboutLayout.setHorizontalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutLayout.createSequentialGroup()
                .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aboutLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(aboutLayout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel2))))
                    .addGroup(aboutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        aboutLayout.setVerticalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        help.setTitle("Ayuda");

        jLabel9.setText("Menu Trabajador");

        jLabel10.setText("Menu DNI");

        jLabel11.setText("Comprueba que los DNI tengan la letra correcta, ");

        jLabel12.setText("corrigiendolos en el excel si fuese necesario");

        jLabel13.setText("Menu IBAN");

        jLabel14.setText("Calcula el IBAN de todos los trabajadores");

        jLabel15.setText("almacenandolo en el excel");

        jLabel16.setText("Menu Correo");

        jLabel17.setText("Genera una direccion de correo para cada ");

        jLabel18.setText("trabajador, guardandola en el excel");

        jLabel19.setText("Menu Nomina");

        jLabel20.setText("Generar Nomina");

        jLabel21.setText("Genera la nomina de cada trabajador");

        jLabel22.setText("Menu Ayuda");

        jLabel23.setText("Menu Ayuda");

        jLabel24.setText("Abre este dialogo :D");

        jLabel25.setText("Menu Información");

        jLabel26.setText("Informacion sobre los creadores");

        jLabel27.setText("Cuando parpadee la pantalla significa que se ha terminado");

        jLabel28.setText("almacenandola en pdf en la carpeta ./Nominas/");

        jLabel29.setText("la accion solicitada y se ha refrescado la tabla con los nuevos datos");

        javax.swing.GroupLayout helpLayout = new javax.swing.GroupLayout(help.getContentPane());
        help.getContentPane().setLayout(helpLayout);
        helpLayout.setHorizontalGroup(
            helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpLayout.createSequentialGroup()
                .addGroup(helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(helpLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel19)
                            .addGroup(helpLayout.createSequentialGroup()
                                .addGroup(helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel28)))))
                    .addGroup(helpLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel27))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        helpLayout.setVerticalGroup(
            helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGroup(helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(helpLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(helpLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGroup(helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(helpLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16))
                    .addGroup(helpLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addGap(5, 5, 5)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ultra Generador de Nominas 9000");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane.setViewportView(jTable);
        fillData();
        model = new DefaultTableModel(data, headers);
        tableWidth = model.getColumnCount() * 150;
        tableHeight = model.getRowCount() * 25;
        jTable.setPreferredSize(new Dimension(tableWidth, tableHeight));
        jTable.setModel(model);
        jTable.setAutoCreateRowSorter(true);
        model = new DefaultTableModel(data, headers);
        jTable.setModel(model);
        jTable.setBackground(Color.LIGHT_GRAY);
        jTable.setAutoResizeMode(jTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable.setEnabled(false);
        jTable.setRowHeight(25);
        jTable.setRowMargin(4);
        tableWidth = model.getColumnCount() * 150;
        tableHeight = model.getRowCount() * 25;
        jTable.setPreferredSize(new Dimension(tableWidth, tableHeight));

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        jMenuTrabajador.setText("Trabajador");

        jMenuDNI.setText("Comprobar DNI");
        jMenuDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDNIActionPerformed(evt);
            }
        });
        jMenuTrabajador.add(jMenuDNI);

        jMenuIBAN.setText("Comprobar IBAN");
        jMenuIBAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIBANActionPerformed(evt);
            }
        });
        jMenuTrabajador.add(jMenuIBAN);

        jMenuCorreo.setText("Generar Correo");
        jMenuCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCorreoActionPerformed(evt);
            }
        });
        jMenuTrabajador.add(jMenuCorreo);

        jMenuBar.add(jMenuTrabajador);

        jMenuNomina.setText("Nómina");

        jMenuGenerarNomina.setText("Generar Nómina");
        jMenuGenerarNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGenerarNominaActionPerformed(evt);
            }
        });
        jMenuNomina.add(jMenuGenerarNomina);

        jMenuBar.add(jMenuNomina);

        jMenuAyuda.setText("Ayuda");

        jMenuAyudaa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuAyudaa.setText("Ayuda");
        jMenuAyudaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAyudaaActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuAyudaa);

        jMenuInformacion.setText("Información");
        jMenuInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInformacionActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuInformacion);

        jMenuBar.add(jMenuAyuda);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDNIActionPerformed
        try {
            ID.checkID();
        } catch (IOException | InvalidFormatException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }//GEN-LAST:event_jMenuDNIActionPerformed

    private void jMenuIBANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIBANActionPerformed
        try {
            Bancos.Validar_cuentas_bancarias();
        } catch (IOException | InvalidFormatException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }//GEN-LAST:event_jMenuIBANActionPerformed

    private void jMenuCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCorreoActionPerformed
        try {
            Correos.Creacion_cuenta_correo();
        } catch (IOException | InvalidFormatException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }//GEN-LAST:event_jMenuCorreoActionPerformed

    private void jMenuGenerarNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGenerarNominaActionPerformed
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        seleccionarFecha.setSize(200, 160);
        final int x = (screenSize.width - seleccionarFecha.getWidth()) / 2;
        final int y = (screenSize.height - seleccionarFecha.getHeight()) / 2;
        seleccionarFecha.setLocation(x, y);    
        seleccionarFecha.setVisible(true);

        if (fecha != "cancel") {
            try {

                String[] fecha_split;
                fecha_split = fecha.split("/");
                Creacion_nominas.Creacion_nominas(fecha_split[0], fecha_split[1]);
                PaysheetToPDF.printPDF(fecha_split);
            } catch (IOException | InvalidFormatException ex) {
                Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
            }
            initComponents();
            this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        }
        fecha="";

    }//GEN-LAST:event_jMenuGenerarNominaActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        fecha = Mes.getSelectedItem().toString() + "/" + Año.getSelectedItem().toString();
        seleccionarFecha.setVisible(false);
        seleccionarFecha.dispose();
    }//GEN-LAST:event_AceptarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        fecha="cancel";
        seleccionarFecha.setVisible(false);
        seleccionarFecha.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void jMenuInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInformacionActionPerformed
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        about.setSize(250, 300);
        final int x = (screenSize.width - about.getWidth()) / 2;
        final int y = (screenSize.height - about.getHeight()) / 2;
        about.setLocation(x, y);   
        about.setVisible(true);
    }//GEN-LAST:event_jMenuInformacionActionPerformed

    private void jMenuAyudaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAyudaaActionPerformed
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        help.setSize(500, 520);
        final int x = (screenSize.width - help.getWidth()) / 2;
        final int y = (screenSize.height - help.getHeight()) / 2;
        help.setLocation(x, y);   
        help.setVisible(true);
    }//GEN-LAST:event_jMenuAyudaaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JComboBox<String> Año;
    private javax.swing.JLabel Añolbl;
    private javax.swing.JButton Cancelar;
    private javax.swing.JComboBox<String> Mes;
    private javax.swing.JLabel Meslbl;
    private javax.swing.JDialog about;
    private javax.swing.JDialog help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuItem jMenuAyudaa;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuCorreo;
    private javax.swing.JMenuItem jMenuDNI;
    private javax.swing.JMenuItem jMenuGenerarNomina;
    private javax.swing.JMenuItem jMenuIBAN;
    private javax.swing.JMenuItem jMenuInformacion;
    private javax.swing.JMenu jMenuNomina;
    private javax.swing.JMenu jMenuTrabajador;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable;
    private javax.swing.JDialog seleccionarFecha;
    // End of variables declaration//GEN-END:variables
}
